name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Python dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      # Install dependencies
      - name: Install dependencies
        run: |
          mkdir package
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./package

      - name: Add Lambda function code
        run: cp src/* ./package/

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:756316131141:function:spotify-data-retriever \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
