name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Python dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      # Install dependencies to a specific directory (package)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./package

      # Copy Lambda function code to package folder
      - name: Copy Lambda function code
        run: cp -r ./src/* ./package/  # Adjust the path as needed

      # Zip the contents of the package folder
      - name: Create Zip file for Lambda function
        run: zip -r code.zip ./package/*

      # Deploy the zip file to Lambda
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:756316131141:function:update_user_spotify_top_items \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
